### PR TITLE
Update SpawnProjectiles.cs

### PR DESCRIPTION
**Pull request by radiatoryang**
change the bullet spawn rotation to match the player's camera, this isn't going to work for NPCs firing bullets because they don't have cameras, so... you'll have to edit this for NPCs too

### CODE REVIEW

**Comment by kreetin7** [comment]
lgtm

**Comment by sparkwon** [comment]
looks like a good fix

**Comment by Chazzmcfreely** [comment]
This seems like a  better fix

**Comment by radiatoryang** [comment]
wow :) :)

**Pull request merged**
