### PR TITLE
Added GameManagerScript, added OnCollisionEnter, added isAlive bool

### PR DESCRIPTION
**Pull request by JCela**
…to check if the player has died or not added isAlive boolean.  When the player dies it resets the scene.  Make sure to have added the scene and the scene number is "1" in the Build settings.  Added the GameManagerScript:  Script that controls the resets of the levels/Winning the level/event system.  isAlive checks if the player collider hits a bullet tag..

### CODE REVIEW

**Comment by kreetin7** [comment]
looks good

**Comment by Chazzmcfreely** [comment]
It's saying this branch has conflicts in
.idea/.idea.SuperHotClone2018/.idea/contentModel.xml
.idea/.idea.SuperHotClone2018/.idea/workspace.xml
Assets/Scenes/TestScene.unity
ProjectSettings/TagManager.asset

**Comment by Chazzmcfreely** [comment]
no conflicts, seems fine

**Comment by SaladProdigy** [comment]
Looks good to me

**Comment by sparkwon** [comment]
Seems good

**Pull request merged**
